name: Sport Analytics CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run frontend tests
        run: >
          docker compose run --rm
          -v ${{ github.workspace }}/frontend/coverage:/app/coverage
          frontend npm test -- --coverage --watchAll=false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./frontend/coverage/lcov.info
          flags: frontend
          fail_ci_if_error: true

  backend-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run backend tests
        run: >
          docker compose run --rm
          -v ${{ github.workspace }}/backend/coverage:/app/coverage
          backend npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: 8d404320-08be-4d89-8672-31835467d45d
          files: ./backend/coverage/lcov.info
          flags: backend
          fail_ci_if_error: true